module.exports = {
  tasks: [
    {
      tasksId: "1",
      task: "Task 1",
      taskDate: "2023-08-29",
      startingTime: 9,
      complete: false,
      estimatedDuration: 60,
      goalId: "G1",
      progress: "In progress",
    },
    {
      tasksId: "2",
      task: "Task 2",
      taskDate: "2023-08-30",
      startingTime: 14,
      complete: true,
      estimatedDuration: 45,
      goalId: "G2",
      progress: "Completed",
    },
    {
      tasksId: "3",
      task: "Task 3",
      taskDate: "2023-08-31",
      startingTime: 10,
      complete: false,
      estimatedDuration: 30,
      goalId: "G1",
      progress: "In progress",
    },
    {
      tasksId: "4",
      task: "Task 4",
      taskDate: "2023-09-01",
      startingTime: 16,
      complete: false,
      estimatedDuration: 90,
      goalId: "G3",
      progress: "Not started",
    },
    {
      tasksId: "5",
      task: "Task 5",
      taskDate: "2023-09-02",
      startingTime: 11,
      complete: true,
      estimatedDuration: 120,
      goalId: "G2",
      progress: "Completed",
    },
    {
      tasksId: "6",
      task: "Task 6",
      taskDate: "2023-09-03",
      startingTime: 8,
      complete: false,
      estimatedDuration: 75,
      goalId: "G3",
      progress: "In progress",
    },
    {
      tasksId: "7",
      task: "Task 7",
      taskDate: "2023-09-04",
      startingTime: 13,
      complete: false,
      estimatedDuration: 60,
      goalId: "G4",
      progress: "Not started",
    },
    {
      tasksId: "8",
      task: "Task 8",
      taskDate: "2023-09-05",
      startingTime: 10,
      complete: true,
      estimatedDuration: 45,
      goalId: "G1",
      progress: "Completed",
    },
    {
      tasksId: "9",
      task: "Task 9",
      taskDate: "2023-09-06",
      startingTime: 15,
      complete: false,
      estimatedDuration: 30,
      goalId: "G3",
      progress: "In progress",
    },
    {
      tasksId: "10",
      task: "Task 10",
      taskDate: "2023-09-07",
      startingTime: 12,
      complete: false,
      estimatedDuration: 90,
      goalId: "G2",
      progress: "Not started",
    },
    {
      tasksId: "11",
      task: "Task 11",
      taskDate: "2023-09-08",
      startingTime: 9,
      complete: true,
      estimatedDuration: 120,
      goalId: "G1",
      progress: "Completed",
    },
    {
      tasksId: "12",
      task: "Task 12",
      taskDate: "2023-09-09",
      startingTime: 14,
      complete: false,
      estimatedDuration: 75,
      goalId: "G4",
      progress: "In progress",
    },
    {
      tasksId: "13",
      task: "Task 13",
      taskDate: "2023-09-10",
      startingTime: 11,
      complete: false,
      estimatedDuration: 60,
      goalId: "G2",
      progress: "Not started",
    },
    {
      tasksId: "14",
      task: "Task 14",
      taskDate: "2023-09-11",
      startingTime: 10,
      complete: true,
      estimatedDuration: 45,
      goalId: "G3",
      progress: "Completed",
    },
    {
      tasksId: "15",
      task: "Task 15",
      taskDate: "2023-09-12",
      startingTime: 16,
      complete: false,
      estimatedDuration: 30,
      goalId: "G1",
      progress: "In progress",
    },
    {
      tasksId: "16",
      task: "Task 16",
      taskDate: "2023-09-13",
      startingTime: 13,
      complete: false,
      estimatedDuration: 90,
      goalId: "G4",
      progress: "Not started",
    },
    {
      tasksId: "17",
      task: "Task 17",
      taskDate: "2023-09-14",
      startingTime: 9,
      complete: true,
      estimatedDuration: 120,
      goalId: "G2",
      progress: "Completed",
    },
    {
      tasksId: "18",
      task: "Task 18",
      taskDate: "2023-09-15",
      startingTime: 14,
      complete: false,
      estimatedDuration: 75,
      goalId: "G1",
      progress: "In progress",
    },
    {
      tasksId: "19",
      task: "Task 19",
      taskDate: "2023-09-16",
      startingTime: 11,
      complete: false,
      estimatedDuration: 60,
      goalId: "G3",
      progress: "Not started",
    },
    {
      tasksId: "20",
      task: "Task 20",
      taskDate: "2023-09-17",
      startingTime: 10,
      complete: true,
      estimatedDuration: 45,
      goalId: "G4",
      progress: "Completed",
    },
  ],
  weeklyGoals: [
    {
      wGoalId: "WG1",
      goal: "Complete Project A",
      urgency: 4,
      importance: 5,
      weekStart: "2023-08-01",
      weekEnd: "2023-08-07",
      completed: false,
      monthlyGoalId: "MG1",
      goalPriority: 1,
      tasks: [
        {
          tasksId: 1,
          task: "Task 1 for Goal 1",
        },
        {
          tasksId: 2,
          task: "Task 2 for Goal 1",
        },
      ],
    },
    {
      wGoalId: "WG2",
      goal: "Read Book X",
      urgency: 3,
      importance: 4,
      weekStart: "2023-08-08",
      weekEnd: "2023-08-14",
      completed: false,
      monthlyGoalId: "MG2",
      goalPriority: 2,
      tasks: [
        {
          tasksId: 3,
          task: "Task 1 for Goal 2",
        },
        {
          tasksId: 4,
          task: "Task 2 for Goal 2",
        },
      ],
    },
    {
      wGoalId: "WG3",
      goal: "Exercise for 30 Minutes",
      urgency: 5,
      importance: 3,
      weekStart: "2023-08-15",
      weekEnd: "2023-08-21",
      completed: false,
      monthlyGoalId: "MG3",
      goalPriority: 3,
      tasks: [
        {
          tasksId: 5,
          task: "Task 1 for Goal 3",
        },
        {
          tasksId: 6,
          task: "Task 2 for Goal 3",
        },
      ],
    },
    {
      wGoalId: "WG4",
      goal: "Learn a New Recipe",
      urgency: 2,
      importance: 4,
      weekStart: "2023-08-22",
      weekEnd: "2023-08-28",
      completed: false,
      monthlyGoalId: "MG4",
      goalPriority: 4,
      tasks: [
        {
          tasksId: 7,
          task: "Task 1 for Goal 4",
        },
        {
          tasksId: 8,
          task: "Task 2 for Goal 4",
        },
      ],
    },
    {
      wGoalId: "WG5",
      goal: "Practice Guitar",
      urgency: 4,
      importance: 3,
      weekStart: "2023-08-29",
      weekEnd: "2023-09-04",
      completed: false,
      monthlyGoalId: "MG5",
      goalPriority: 5,
      tasks: [
        {
          tasksId: 9,
          task: "Task 1 for Goal 5",
        },
        {
          tasksId: 10,
          task: "Task 2 for Goal 5",
        },
      ],
    },
    {
      wGoalId: "WG6",
      goal: "Write a Blog Post",
      urgency: 3,
      importance: 4,
      weekStart: "2023-09-05",
      weekEnd: "2023-09-11",
      completed: false,
      monthlyGoalId: "MG6",
      goalPriority: 6,
      tasks: [
        {
          tasksId: 11,
          task: "Task 1 for Goal 6",
        },
        {
          tasksId: 12,
          task: "Task 2 for Goal 6",
        },
      ],
    },
    {
      wGoalId: "WG7",
      goal: "Organize Wardrobe",
      urgency: 2,
      importance: 3,
      weekStart: "2023-09-12",
      weekEnd: "2023-09-18",
      completed: false,
      monthlyGoalId: "MG7",
      goalPriority: 7,
      tasks: [
        {
          tasksId: 13,
          task: "Task 1 for Goal 7",
        },
        {
          tasksId: 14,
          task: "Task 2 for Goal 7",
        },
      ],
    },
    {
      wGoalId: "WG8",
      goal: "Study a New Language",
      urgency: 4,
      importance: 5,
      weekStart: "2023-09-19",
      weekEnd: "2023-09-25",
      completed: false,
      monthlyGoalId: "MG8",
      goalPriority: 8,
      tasks: [
        {
          tasksId: 15,
          task: "Task 1 for Goal 8",
        },
        {
          tasksId: 16,
          task: "Task 2 for Goal 8",
        },
      ],
    },
    {
      wGoalId: "WG9",
      goal: "Read a Research Paper",
      urgency: 3,
      importance: 4,
      weekStart: "2023-09-26",
      weekEnd: "2023-10-02",
      completed: false,
      monthlyGoalId: "MG9",
      goalPriority: 9,
      tasks: [
        {
          tasksId: 17,
          task: "Task 1 for Goal 9",
        },
        {
          tasksId: 18,
          task: "Task 2 for Goal 9",
        },
      ],
    },
    {
      wGoalId: "WG10",
      goal: "Create a Digital Painting",
      urgency: 4,
      importance: 3,
      weekStart: "2023-10-03",
      weekEnd: "2023-10-09",
      completed: false,
      monthlyGoalId: "MG10",
      goalPriority: 10,
      tasks: [
        {
          tasksId: 19,
          task: "Task 1 for Goal 10",
        },
        {
          tasksId: 20,
          task: "Task 2 for Goal 10",
        },
      ],
    },
  ],
  monthlyGoals: [
    {
      mGoalId: "MG1",
      goal: "Read 3 Books",
      urgency: 4,
      importance: 5,
      tasksInGoal: '["Book A", "Book B", "Book C"]',
      estimatePeriodPerDay: 30,
      complete: false,
      goalPriority: 1,
      goalCategory: "PERSONAL",
      username: "user123",
      privacy: "PRIVATE",
      monthStart: "2023-08-01",
    },
    {
      mGoalId: "MG2",
      goal: "Exercise 3 Times a Week",
      urgency: 3,
      importance: 4,
      tasksInGoal: '["Gym", "Running", "Yoga"]',
      estimatePeriodPerDay: 45,
      complete: false,
      goalPriority: 2,
      goalCategory: "FITNESS",
      username: "user456",
      privacy: "PUBLIC",
      monthStart: "2023-08-01",
    },
    {
      mGoalId: "MG3",
      goal: "Finish Project X",
      urgency: 5,
      importance: 3,
      tasksInGoal: '["Task 1", "Task 2", "Task 3"]',
      estimatePeriodPerDay: 60,
      complete: false,
      goalPriority: 3,
      goalCategory: "PROJECT",
      username: "user789",
      privacy: "PERSONAL",
      monthStart: "2023-08-01",
    },
    {
      mGoalId: "MG4",
      goal: "Cook New Recipes",
      urgency: 2,
      importance: 4,
      tasksInGoal: '["Recipe A", "Recipe B", "Recipe C"]',
      estimatePeriodPerDay: 30,
      complete: false,
      goalPriority: 4,
      goalCategory: "OTHER",
      username: "user123",
      privacy: "PRIVATE",
      monthStart: "2023-08-01",
    },
    {
      mGoalId: "MG5",
      goal: "Spend Quality Time with Family",
      urgency: 4,
      importance: 4,
      tasksInGoal: '["Game Night", "Outdoor Activity", "Cook Together"]',
      estimatePeriodPerDay: 45,
      complete: false,
      goalPriority: 5,
      goalCategory: "FAMILY",
      username: "user456",
      privacy: "PUBLIC",
      monthStart: "2023-08-01",
    },
  ],
  notes: [
    {
      noteId: 1,
      title: "Project Kickoff",
      note: "Discussion about project goals and initial planning.",
      dateCreated: "2023-08-30",
      media: [
        {
          name: "MeetingPhoto",
          type: "image",
          location: "/media/images/meeting1.jpg",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Emily Johnson",
    },
    {
      noteId: 2,
      title: "Ideation Session",
      note: "Generated ideas for the upcoming marketing campaign.",
      dateCreated: "2023-08-29",
      media: [
        {
          name: "Whiteboard1",
          type: "image",
          location: "/media/images/whiteboard1.jpg",
        },
        {
          name: "Whiteboard2",
          type: "image",
          location: "/media/images/whiteboard2.jpg",
        },
      ],
      notePrivacy: "PUBLIC",
      creator: "Alex Miller",
    },
    {
      noteId: 3,
      title: "User Research",
      note: "Collected user feedback from recent app usability testing.",
      dateCreated: "2023-08-28",
      media: [
        {
          name: "FeedbackAudio",
          type: "audio",
          location: "/media/audio/feedback1.mp3",
        },
        {
          name: "UserResponses",
          type: "document",
          location: "/media/documents/user_responses.pdf",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Sophia Lee",
    },
    {
      noteId: 4,
      title: "Design Iterations",
      note: "Explored multiple design options for the website's landing page.",
      dateCreated: "2023-08-27",
      media: [
        {
          name: "DesignOption1",
          type: "image",
          location: "/media/images/design1.jpg",
        },
        {
          name: "DesignOption2",
          type: "image",
          location: "/media/images/design2.jpg",
        },
        {
          name: "DesignOption3",
          type: "image",
          location: "/media/images/design3.jpg",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Daniel Brown",
    },
    {
      noteId: 5,
      title: "Financial Planning",
      note: "Outlined budget allocation for the next fiscal year.",
      dateCreated: "2023-08-26",
      media: [
        {
          name: "BudgetSpreadsheet",
          type: "document",
          location: "/media/documents/budget.xlsx",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Olivia Martinez",
    },
    {
      noteId: 6,
      title: "Client Meeting",
      note: "Discussed project updates and upcoming milestones with the client.",
      dateCreated: "2023-08-25",
      media: [
        {
          name: "MeetingRecording",
          type: "video",
          location: "/media/videos/meeting2.mp4",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "William Johnson",
    },
    {
      noteId: 7,
      title: "Content Ideas",
      note: "Brainstormed content topics for the company blog.",
      dateCreated: "2023-08-24",
      media: [
        {
          name: "Notebook",
          type: "image",
          location: "/media/images/notebook1.jpg",
        },
      ],
      notePrivacy: "PUBLIC",
      creator: "Emma Thompson",
    },
    {
      noteId: 8,
      title: "Product Concepts",
      note: "Outlined potential features and improvements for the product.",
      dateCreated: "2023-08-23",
      media: [
        {
          name: "ConceptSketch",
          type: "image",
          location: "/media/images/concept1.jpg",
        },
        {
          name: "FeatureList",
          type: "document",
          location: "/media/documents/features.docx",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Aiden Wilson",
    },
    {
      noteId: 9,
      title: "Team Building",
      note: "Logged team-building activities and ideas for the next retreat.",
      dateCreated: "2023-08-22",
      media: [
        {
          name: "TeamPhoto",
          type: "image",
          location: "/media/images/team1.jpg",
        },
        {
          name: "RetreatIdeas",
          type: "document",
          location: "/media/documents/retreat_ideas.pdf",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Mia Davis",
    },
    {
      noteId: 10,
      title: "Research Findings",
      note: "Summarized findings from a recent market research study.",
      dateCreated: "2023-08-21",
      media: [
        {
          name: "ResearchReport",
          type: "document",
          location: "/media/documents/research_report.pdf",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Ethan Jones",
    },
    {
      noteId: 11,
      title: "Project Update",
      note: "Provided stakeholders with an update on project status.",
      dateCreated: "2023-08-20",
      media: [
        {
          name: "SlidePresentation",
          type: "document",
          location: "/media/documents/presentation.pptx",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Ava Smith",
    },
    {
      noteId: 12,
      title: "Creative Brainstorm",
      note: "Generated creative ideas for the upcoming ad campaign.",
      dateCreated: "2023-08-19",
      media: [
        {
          name: "CreativeIdeas",
          type: "document",
          location: "/media/documents/creative_ideas.docx",
        },
      ],
      notePrivacy: "PUBLIC",
      creator: "Noah Brown",
    },
    {
      noteId: 13,
      title: "Customer Feedback",
      note: "Compiled customer feedback from social media and surveys.",
      dateCreated: "2023-08-18",
      media: [
        {
          name: "FeedbackSurveyResults",
          type: "document",
          location: "/media/documents/feedback_results.xlsx",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Isabella Johnson",
    },
    {
      noteId: 14,
      title: "Training Session",
      note: "Notes from the recent training session on new software.",
      dateCreated: "2023-08-17",
      media: [
        {
          name: "TrainingSlides",
          type: "document",
          location: "/media/documents/training_slides.pdf",
        },
        {
          name: "TrainingRecording",
          type: "video",
          location: "/media/videos/training.mp4",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "James Miller",
    },
    {
      noteId: 15,
      title: "Marketing Strategies",
      note: "Outlined strategies for the upcoming product launch.",
      dateCreated: "2023-08-16",
      media: [
        {
          name: "MarketingPlan",
          type: "document",
          location: "/media/documents/marketing_plan.docx",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Sophia Williams",
    },
    {
      noteId: 16,
      title: "Design Inspiration",
      note: "Collected design inspiration for the new website layout.",
      dateCreated: "2023-08-15",
      media: [
        {
          name: "DesignInspirations",
          type: "image",
          location: "/media/images/inspirations.jpg",
        },
      ],
      notePrivacy: "PUBLIC",
      creator: "Elijah Martinez",
    },
    {
      noteId: 17,
      title: "Quarterly Goals",
      note: "Outlined company goals and targets for the next quarter.",
      dateCreated: "2023-08-14",
      media: [
        {
          name: "GoalPresentation",
          type: "document",
          location: "/media/documents/goals.pptx",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Avery Taylor",
    },
    {
      noteId: 18,
      title: "Client Feedback",
      note: "Logged feedback and suggestions from recent client meetings.",
      dateCreated: "2023-08-13",
      media: [
        {
          name: "ClientFeedback",
          type: "document",
          location: "/media/documents/client_feedback.docx",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Jackson Davis",
    },
    {
      noteId: 19,
      title: "Product Roadmap",
      note: "Discussed the roadmap for upcoming product releases.",
      dateCreated: "2023-08-12",
      media: [
        {
          name: "RoadmapDiagram",
          type: "image",
          location: "/media/images/roadmap.png",
        },
        {
          name: "ReleasePlan",
          type: "document",
          location: "/media/documents/release_plan.docx",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Scarlett Wilson",
    },
    {
      noteId: 20,
      title: "Team Meeting",
      note: "Shared updates and action items from the weekly team meeting.",
      dateCreated: "2023-08-11",
      media: [
        {
          name: "MeetingNotes",
          type: "document",
          location: "/media/documents/meeting_notes.docx",
        },
      ],
      notePrivacy: "PRIVATE",
      creator: "Lucas Johnson",
    },
  ],
  expenses: [
    {
      expenseId: "exp1",
      budgetId: "budget2023",
      item: "Office Supplies",
      amount: 250.75,
      expenseDate: "2023-08-30",
      expenseType: "PURCHASE",
      expenseCategory: "OFFICE",
      expensePrivacy: "PRIVATE",
      creator: "Emily Johnson",
    },
    {
      expenseId: "exp2",
      budgetId: "budget2023",
      item: "Travel Expenses",
      amount: 1200.5,
      expenseDate: "2023-08-29",
      expenseType: "TRAVEL",
      expenseCategory: "BUSINESS",
      expensePrivacy: "PRIVATE",
      creator: "Alex Miller",
    },
    {
      expenseId: "exp3",
      budgetId: "budget2023",
      item: "Marketing Campaign",
      amount: 3500.0,
      expenseDate: "2023-08-28",
      expenseType: "MARKETING",
      expenseCategory: "ADVERTISING",
      expensePrivacy: "PRIVATE",
      creator: "Sophia Lee",
    },
    {
      expenseId: "exp4",
      budgetId: "budget2023",
      item: "Team Lunch",
      amount: 150.25,
      expenseDate: "2023-08-27",
      expenseType: "MEAL",
      expenseCategory: "TEAM",
      expensePrivacy: "PRIVATE",
      creator: "Daniel Brown",
    },
    {
      expenseId: "exp5",
      budgetId: "budget2023",
      item: "Software Subscription",
      amount: 99.99,
      expenseDate: "2023-08-26",
      expenseType: "SUBSCRIPTION",
      expenseCategory: "TECHNOLOGY",
      expensePrivacy: "PRIVATE",
      creator: "Olivia Martinez",
    },
    {
      expenseId: "exp6",
      budgetId: "budget2023",
      item: "Client Dinner",
      amount: 320.0,
      expenseDate: "2023-08-25",
      expenseType: "MEAL",
      expenseCategory: "CLIENT",
      expensePrivacy: "PRIVATE",
      creator: "William Johnson",
    },
    {
      expenseId: "exp7",
      budgetId: "budget2023",
      item: "Printing Services",
      amount: 180.5,
      expenseDate: "2023-08-24",
      expenseType: "SERVICE",
      expenseCategory: "ADMINISTRATION",
      expensePrivacy: "PUBLIC",
      creator: "Emma Thompson",
    },
    {
      expenseId: "exp8",
      budgetId: "budget2023",
      item: "Conference Registration",
      amount: 750.0,
      expenseDate: "2023-08-23",
      expenseType: "EVENT",
      expenseCategory: "PROFESSIONAL",
      expensePrivacy: "PRIVATE",
      creator: "Aiden Wilson",
    },
    {
      expenseId: "exp9",
      budgetId: "budget2023",
      item: "Office Rent",
      amount: 4500.0,
      expenseDate: "2023-08-22",
      expenseType: "RENT",
      expenseCategory: "FACILITY",
      expensePrivacy: "PRIVATE",
      creator: "Mia Davis",
    },
    {
      expenseId: "exp10",
      budgetId: "budget2023",
      item: "Training Course",
      amount: 300.0,
      expenseDate: "2023-08-21",
      expenseType: "TRAINING",
      expenseCategory: "PERSONAL_DEVELOPMENT",
      expensePrivacy: "PRIVATE",
      creator: "Ethan Jones",
    },
  ],
  budget: [
    {
      budgetId: "b2023q3",
      budget: "Q3 Expenses",
      amount: 15000.0,
      dateOfPayment: "2023-07-01",
      goalId: "g345",
      paid: true,
      expenseCategory: "OPERATIONAL",
      budgetPrivacy: "PRIVATE",
      creator: "Emily Johnson",
    },
    {
      budgetId: "b2023q4",
      budget: "Year-End Budget",
      amount: 25000.0,
      dateOfPayment: "2023-10-01",
      goalId: "g456",
      paid: false,
      expenseCategory: "ADMINISTRATION",
      budgetPrivacy: "PRIVATE",
      creator: "Alex Miller",
    },
    {
      budgetId: "b2023q4",
      budget: "Holiday Party",
      amount: 1200.0,
      dateOfPayment: "2023-12-15",
      goalId: "g456",
      paid: false,
      expenseCategory: "TEAM",
      budgetPrivacy: "PUBLIC",
      creator: "Sophia Lee",
    },
    {
      budgetId: "b2023q3",
      budget: "Marketing Campaign",
      amount: 5000.0,
      dateOfPayment: "2023-06-15",
      goalId: "g345",
      paid: true,
      expenseCategory: "MARKETING",
      budgetPrivacy: "PRIVATE",
      creator: "Daniel Brown",
    },
    {
      budgetId: "b2023q3",
      budget: "Research and Development",
      amount: 8000.0,
      dateOfPayment: "2023-07-31",
      goalId: "g345",
      paid: true,
      expenseCategory: "DEVELOPMENT",
      budgetPrivacy: "PRIVATE",
      creator: "Olivia Martinez",
    },
    {
      budgetId: "b2023q4",
      budget: "Office Upgrades",
      amount: 3000.0,
      dateOfPayment: "2023-11-05",
      goalId: "g456",
      paid: false,
      expenseCategory: "FACILITY",
      budgetPrivacy: "PRIVATE",
      creator: "William Johnson",
    },
    {
      budgetId: "b2023q4",
      budget: "Training and Development",
      amount: 1500.0,
      dateOfPayment: "2023-11-20",
      goalId: "g456",
      paid: true,
      expenseCategory: "PERSONAL_DEVELOPMENT",
      budgetPrivacy: "PRIVATE",
      creator: "Emma Thompson",
    },
    {
      budgetId: "b2023q3",
      budget: "Travel Expenses",
      amount: 4000.0,
      dateOfPayment: "2023-07-10",
      goalId: "g345",
      paid: true,
      expenseCategory: "TRAVEL",
      budgetPrivacy: "PUBLIC",
      creator: "Aiden Wilson",
    },
    {
      budgetId: "b2023q4",
      budget: "IT Infrastructure",
      amount: 6000.0,
      dateOfPayment: "2023-10-15",
      goalId: "g456",
      paid: false,
      expenseCategory: "TECHNOLOGY",
      budgetPrivacy: "PRIVATE",
      creator: "Mia Davis",
    },
    {
      budgetId: "b2023q4",
      budget: "Community Events",
      amount: 1800.0,
      dateOfPayment: "2023-12-10",
      goalId: "g456",
      paid: false,
      expenseCategory: "COMMUNITY",
      budgetPrivacy: "PRIVATE",
      creator: "Ethan Jones",
    },
  ],
};
